apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
      # Tell k8s-publisher to send notifications of failure to slack #my-channel
    notify-channels: |
      [{"type":"slack", "value":"#my-channel"}]
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always